### ISSUE TITLE
source maps don't work out of the box

### ISSUE THREAD

**Issue by gabimor** [nuxt-community/storybook#187]
When storybook fails on a story, it show a stack trace of the built bundle instead of using the source maps.
I'd like to see a stack trace of my code before the builing process

Nuxt-storybook: 3.2
Language: Typescript
Example stacktrace shown:

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Proxy.render (http://localhost:3003/main.f4a614da9096015b11ee.bundle.js:64062:20)
    at http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:58568:80
    at activateCurrentInstance (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:58528:16)
    at Proxy.$options.render (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:58568:24)
    at VueComponent.Vue._render (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:334712:22)
    at VueComponent.updateComponent (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:335230:21)
    at Watcher.get (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:335643:25)
    at new Watcher (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:335632:12)
    at mountComponent (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:335237:3)
    at VueComponent.push../node_modules/vue/dist/vue.esm.js.Vue.$mount (http://localhost:3003/vendors~main.f4a614da9096015b11ee.bundle.js:340214:10)

**Comment by farnabaz** [comment]
Could you provide a reproduction sample? Stack traces were fine in my attempts
