### ISSUE TITLE
Storybook needs either a "main" or "config" file.

### ISSUE THREAD

**Issue by nevadavid** [nuxt-community/storybook#273]
### Version
@nuxtjs/storybook: ^4.0.2
nuxt: ^2.15.4

### Steps to reproduce
1. Followed basic setup steps.
2. Add .storybook/preview.js file like this: https://storybook.js.org/docs/vue/essentials/toolbars-and-globals#advanced-usage

### What is Expected?
Storybook to run.

### What is actually happening?
```
ERR! Error: No configuration files have been found in your configDir (/home/david/Work/nuxt/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/presets.js:310:105)
ERR!     at buildDevStandalone (/home/david/Work/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:98:48)
ERR!     at async Object.buildDev (/home/david/Work/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:147:5)
ERR!  Error: No configuration files have been found in your configDir (/home/david/Work/nuxt/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets (/home/david/Work/nuxt/node_modules/@storybook/core-common/dist/cjs/presets.js:310:105)
ERR!     at buildDevStandalone (/home/david/Work/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:98:48)
ERR!     at async Object.buildDev (/home/david/Work/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:147:5)
```

**Comment by nevadavid** [comment]
I use this example solved my problem: https://github.com/tim-kilian/nuxt-storybook-i18n-example
