### ISSUE TITLE
[4.0.4] TypeError: Router.use() requires a middleware function but got a undefined

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-community/storybook#285]
I still have issue #275 with version `4.0.4`. This is [my serverMiddleware](https://github.com/maevsi/maevsi/blob/2255ecc4f564c50c1ca24a92602acdb3316e23a4/nuxt/nuxt.config.js#L354):

```
import bodyParser from 'body-parser'

export default {
  serverMiddleware: [
    bodyParser.json(),
    '~/middleware/server/headers.ts',
  ],
}
```

Commenting out either middleware does not fix the issue.

**Comment by drewbaker** [comment]
Can confirm that I guess this error too. Although if I comment out my serverMiddleware it works.

**Comment by artmizu** [comment]
@dargmuesli @drewbaker 

as a temporary workaround you may install the nuxt-storybook through a [manual setup](https://storybook.nuxtjs.org/manual-setup/). In the manual way you can disable a server side middleware. It worked for me.

**Comment by dargmuesli** [comment]
@artmizu how does one disable a server side middleware when using the manual setup? I already ran `eject`.

**Comment by dargmuesli** [comment]
Forgive me if I'm wrong, but there hasn't been any release, has it?

**Comment by dargmuesli** [comment]
Thanks a lot. If you got time and it's possible, Storybook 6.3 support would make me very happy too :) It might resolve some of the recently reported reload-loop issues too.

**Comment by productfrontenddeveloper** [comment]
> Sorry for the being late @dargmuesli, I couldn't manage to release the new version.
> I will release it today or tomorrow and will ping you

v6.3.2 updated new version ?

**Comment by farnabaz** [comment]
Sorry for delay guys @productfrontenddeveloper @drewbaker 

Just released https://github.com/nuxt-community/storybook/releases/tag/v4.1.0

**Comment by dargmuesli** [comment]
With version 4.1.1 I now get the following error

```
ERR!  TypeError: Router.use() requires a middleware function but got a undefined
ERR!     at Function.use (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/express/lib/router/index.js:458:13)
ERR!     at addServerMiddleware (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:24:9)
ERR!     at /mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:27:28
ERR!     at Array.forEach (<anonymous>)
ERR!     at module.exports (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:27:15)
ERR!     at storybookDevServer (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/dev-server.js:82:52)
ERR!     at buildDevStandalone (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
ERR!     at Object.buildDev (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
ERR!  TypeError: Router.use() requires a middleware function but got a undefined
ERR!     at Function.use (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/express/lib/router/index.js:458:13)
ERR!     at addServerMiddleware (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:24:9)
ERR!     at /mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:27:28
ERR!     at Array.forEach (<anonymous>)
ERR!     at module.exports (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/.nuxt-storybook/storybook/middleware.js:27:15)
ERR!     at storybookDevServer (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/dev-server.js:82:52)
ERR!     at buildDevStandalone (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
ERR!     at Object.buildDev (/mnt/data/WorkingDirectory/Git/maevsi/maevsi/nuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
```

with this serverMiddleware:

```
  serverMiddleware: [
    bodyParser.json(),
    '~/middleware/server/headers.ts',
    { path: '/auth', handler: '~/api/auth.ts' },
    { path: '/ical', handler: '~/api/ical.ts' },
    { path: '/tusd', handler: '~/api/tusd.ts' },
  ],
```

It looks like the line `'~/middleware/server/headers.ts'` causes the error, because here: https://github.com/nuxt-community/storybook/blob/c0946cd8ad6ead2e12dedc5fb9a51a20cd52c687/storybook/middleware.js#L9-L13 the file is required, but does not expose properties like `handler, handle, path, route`:

```
// headers.ts
import { IncomingMessage, ServerResponse } from 'http'

export default function (
  _req: IncomingMessage,
  res: ServerResponse,
  next: any
) {
  res.setHeader('Permissions-Policy', '')
  next()
}
```

**Comment by dargmuesli** [comment]
Oh, got it. Changing this:
```
  serverMiddleware: [
    '~/middleware/server/headers.ts',
  ],
```

to this:

```
  serverMiddleware: [
    { handler: '~/middleware/server/headers.ts' },
  ],
```

Resolves the issue. I'll still open a new issue for this though, just in case you want to support the string only notation too.
