### ISSUE TITLE
Cannot read property 'preference' of undefined

### ISSUE THREAD

**Issue by liyasthomas** [nuxt-community/storybook#306]
### Version
@nuxtjs/storybook: v4.1.1 (latest version)
nuxt: v2.15.7 (latest version, SPA mode)

### Reproduction Link
NA

### Steps to reproduce
I was trying to add `@nuxtjs/storybook` to [my Nuxt project](https://github.com/hoppscotch/hoppscotch).

I made a simple test component in `components/MyButton.vue`
```
<template>
  <button><slot/></button>
</template>
```

and a story in `components/MyButton.stories.js`
```
export default {
  title: "MyButton",
}

export const MyButton = () => "<MyButton>Primary Button</MyButton>"
```

`nuxt.config.js`
```
export default {
...
components: true,
...
storybook: {
    webpackFinal(config, _options) {
      config.node = {
        fs: "empty",
      }

      // extend config here
      return config
    },
  },
...
}
```

then ran `npx nuxt storybook`

### What is Expected?
Storybook should render `MyButton.vue` component.

### What is actually happening?
Throwing an error:
```
Cannot read property 'preference' of undefined

TypeError: Cannot read property 'preference' of undefined
    at http://localhost:3003/main.iframe.bundle.js:954:29
    at _callee2$ (http://localhost:3003/main.iframe.bundle.js:3719:110)
    at tryCatch (http://localhost:3003/vendors~main.iframe.bundle.js:276534:17)
    at Generator.invoke [as _invoke] (http://localhost:3003/vendors~main.iframe.bundle.js:276751:22)
    at Generator.next (http://localhost:3003/vendors~main.iframe.bundle.js:276587:21)
    at asyncGeneratorStep (http://localhost:3003/vendors~main.iframe.bundle.js:7544:24)
    at _next (http://localhost:3003/vendors~main.iframe.bundle.js:7566:9)
````

### Screenshots

<img width="1440" alt="Screenshot 2021-07-16 at 11 58 23 AM" src="https://user-images.githubusercontent.com/10395817/125902422-6c69e46b-fdaa-4339-b659-a6cebe22620e.png">

**Comment by liyasthomas** [comment]
Closing this issue since this is not related to `@nuxtjs/storybook`. [This is a known issue](https://github.com/nuxt-community/color-mode-module/issues/69) in `https://github.com/nuxt-community/color-mode-module` and already have an [open fix PR](https://github.com/nuxt-community/color-mode-module/pull/99).

To fix this temporary issue, downgrade `@nuxtjs/color-mode-module`. Please refer to:  https://github.com/nuxt-community/color-mode-module/issues/69#issuecomment-860681973
