### ISSUE TITLE
Error: Trace: The node type SpreadProperty has been renamed to SpreadElement

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/storybook#66]
### Version

Nuxt install with these dependencies.

```
"dependencies": {
        "@nuxtjs/device": "^1.2.7",
        "cheerio": "^1.0.0-rc.3",
        "core-js": "^3.6.5",
        "graphql": "^15.3.0",
        "graphql-tag": "^2.11.0",
        "lodash": "^4.17.19",
        "node-fetch": "^2.4.1",
        "nuxt": "^2.14.1",
        "nuxt-basic-auth-module": "^1.3.2",
        "nuxt-graphql-request": "^3.0.0",
        "sanitize-html": "^1.27.2"
    },
    "devDependencies": {
        "@nuxtjs/storybook": "^1.2.0",
        "@nuxtjs/style-resources": "^1.0.0",
        "babel-plugin-transform-object-rest-spread": "^6.26.0",
        "eslint": "^7.6.0",
        "eslint-plugin-vue": "^6.2.2",
        "node-sass": "^4.14.1",
        "nodemon": "^2.0.4",
        "prettier": "^2.0.5",
        "prettier-eslint": "^11.0.0",
        "sass-loader": "^9.0.3",
        "svg-inline-loader": "^0.8.2",
        "webfontloader": "^1.6.28"
    }
```

### Steps to reproduce

Install this repo: https://github.com/funkhaus/fuxt/tree/storybook

Install dependencies and then run `npx nuxt stroybook`

### What is Expected?

Storybook builds and works.

### What is actually happening?

Build crashes with this error:

```
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/types/lib/validators/generated/
index.js:4624:11)
    at hasSpread (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/babel-plugin-transform-object-rest-spread/lib/index.
js:38:13)
    at PluginPass.ObjectExpression (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/babel-plugin-transform-object-rest
-spread/lib/index.js:234:14)
    at newFn (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/visitors.js:175:21)

    at NodePath._call (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:112
:16)
    at TraversalContext.visitSingle (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:84
:19)
    at TraversalContext.visit (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:112
:16)
    at TraversalContext.visitMultiple (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:
79:17)
    at TraversalContext.visit (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/traverse/lib/index.js:82:17)
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/Users/drew/Sites/makemake-entertainment-frontend/node_modules/@babel/types/lib/validators/generated/
index.js:4624:11)

... and so on forever
```

I think it's unrelated, but I also can't get Nuxt Storybook to import `.gql` files, I get module not found errors. They work fine in regular Nuxt (that's what `graphql-tag` does).

**Comment by drewbaker** [comment]
Repo here: https://github.com/funkhaus/fuxt/tree/storybook

**Comment by drewbaker** [comment]
Fixed by running `npm outdated` and manually upping version numbers on everything, then setting this in my nuxt.config.js file:

```
    storybook: {
        webpackFinal(config, { configDir }) {
            // Allow webpack to auto-load .gql files
            config.resolve.extensions.push(".gql")

            return config
        }
    }
```

**Comment by farnabaz** [comment]
Glad to hear it 👍 

The main issue is that you were using `babel-plugin-transform-object-rest-spread` that is outdated. Using `@babel/plugin-proposal-object-rest-spread` is recommended.

**Comment by drewbaker** [comment]
Thanks @farnabaz i’ll switch that out.

**Comment by drewbaker** [comment]
If I run `npm uninstall babel-plugin-transform-object-rest-spread` then `npm install -d @babel/plugin-proposal-object-rest-spread` then `npm run dev` I get this error:

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):                                       friendly-errors 19:32:24
Error: Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/drew/Sites/fuxt'
    at Function.resolveSync [as sync] (/Users/drew/Sites/fuxt/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)

    at /Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at cachedFunction (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/drew/Sites/fuxt/node_modules/gensync/index.js:244:28)
    at sync (/Users/drew/Sites/fuxt/node_modules/gensync/index.js:84:14)
    at plugins (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/Users/drew/Sites/fuxt/node_modules/@babel/core/lib/config/config-chain.js:383:26)
```

Which is weird, it seems like `babel-plugin-transform-object-rest-spread` is needed still.

**Comment by drewbaker** [comment]
Nevermind, figured it out, needed this in my `nuxt.config.js`:

```
    build: {
        babel: {
            plugins: ["@babel/plugin-proposal-object-rest-spread"]
        }
```
